version: 0.0
os: windows
files:
  - source: /
    destination: C:\
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 100
      runas: root
    - location: scripts/start_server
      timeout: 100
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 100
      runas: root
